### ISSUE TITLE
No script named 'picopayments-cli'

### ISSUE THREAD

**Issue by unsystemizer** [F483/picopayments-cli-python#11]
* Ubuntu 16.04.1 LTS
* Python 3.5.2
* Installed both from the source (tests passed) and the CLI (both as root and as a sudoer).

```
$ picopayments-cli --testnet status
Traceback (most recent call last):
  File "/usr/local/bin/picopayments-cli", line 4, in <module>
    __import__('pkg_resources').run_script('picopayments-cli==0.0.20', 'picopayments-cli')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1490, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'picopayments-cli'
```

Re-install attempt (after which I still get the above error):

```
$ sudo pip3 install picopayments-cli
Requirement already satisfied: picopayments-cli in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: json-rpc>=1.10.3 in /usr/local/lib/python3.5/dist-packages/json_rpc-1.10.3-py3.5.egg (from picopayments-cli)
Requirement already satisfied: micropayment-core>=0.4.3 in /usr/local/lib/python3.5/dist-packages (from picopayments-cli)
Requirement already satisfied: pyelliptic>=1.5.7 in /usr/local/lib/python3.5/dist-packages (from picopayments-cli)
Requirement already satisfied: ecdsa>=0.13 in /usr/local/lib/python3.5/dist-packages (from picopayments-cli)
Requirement already satisfied: pycoin==0.70 in /usr/local/lib/python3.5/dist-packages (from picopayments-cli)
$ sudo pip3 list | grep picopayments-cli
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
picopayments-cli (0.0.20)
```

**Comment by F483** [comment]
Can you try again after upgrading? I fixed one issue but am not sure if it will help you.

`sudo pip3 install picopayments-cli --upgrade`

**Comment by unsystemizer** [comment]
Works now (I installed in another environment, though, without making an upgrade)
