### ISSUE TITLE
Error No Requests

### ISSUE THREAD

**Issue by tempestb** [F483/picopayments-cli-python#17]
picopayments-cli --testnet status
Traceback (most recent call last):
  File "/usr/local/bin/picopayments-cli", line 10, in <module>
    from picopayments_cli import api
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/api.py", line 8, in <module>
    from picopayments_cli.rpc import JsonRpc
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/rpc.py", line 8, in <module>
    import requests
ImportError: No module named 'requests'

Just following the testing guide in the Github.  Not sure if I missed any prerequisites?

**Comment by F483** [comment]
I added the missing requirement, can you reinstall and see if it fixes your problem?

```
$ sudo pip install picopayments-cli --upgrade
$ picopayments-cli version
"0.2.1"
```

In the output of `pip freeze` you should be able to find `requests==2.12.4`

**Comment by tempestb** [comment]
That fixed it.  Much appreciated!

**Comment by F483** [comment]
Thank you for the bug report!
