### ISSUE TITLE
Good error message if connect fails because of insufficient funds.

### ISSUE THREAD

**Issue by F483** [F483/picopayments-cli-python#3]
This is a common use case and should have a good clear error to help users.

**Comment by littleskunk** [comment]
Error message looks like this:
```
root@micropayment:~/.picopayments# picopayments-cli --testnet connect XCP 1000000
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:732: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html (This warning will only appear once by default.)
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/usr/local/bin/picopayments-cli", line 21, in <module>
    result = api.__getattribute__(command)(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/api.py", line 152, in connect
    asset=asset, delay_time=delay_time)
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/mph.py", line 68, in connect
    c2h_deposit_rawtx = self._make_deposit()
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/mph.py", line 259, in _make_deposit
    quantity=self.c2h_deposit_quantity
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/rpc.py", line 90, in wrapper
    password=self.password
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/rpc.py", line 53, in auth_jsonrpc_call
    password=password, verify_ssl_cert=verify_ssl_cert)
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/rpc.py", line 42, in jsonrpc_call
    raise JsonRpcCallFailed(payload, response)
picopayments_cli.rpc.JsonRpcCallFailed: Rpc call failed! {'jsonrpc': '2.0', 'params': {'spend_secret_hash': '3af9eead9915a477c49ab2bbb66e2967401c5ea6', 'payer_pubkey': '032e23f28e9595b30f38f92d30286789713092f3706816300ea4bb1a080d8ba443', 'expire_time': 1024, 'payee_pubkey': '02b411c282202d2496117f171fb889d6eb4c66a98a3c1ece5a1ca58891f4a92261', 'asset': 'XCP', 'quantity': 1000000}, 'method': 'mpc_make_deposit', 'id': 0} -> {'jsonrpc': '2.0', 'id': 0, 'error': {'code': -32000, 'message': 'Server error', 'data': {'type': 'JsonRpcCallFailed', 'message': 'Rpc call failed! {\'jsonrpc\': \'2.0\', \'params\': {\'spend_secret_hash\': \'3af9eead9915a477c49ab2bbb66e2967401c5ea6\', \'expire_time\': 1024, \'asset\': \'XCP\', \'payee_pubkey\': \'02b411c282202d2496117f171fb889d6eb4c66a98a3c1ece5a1ca58891f4a92261\', \'payer_pubkey\': \'032e23f28e9595b30f38f92d30286789713092f3706816300ea4bb1a080d8ba443\', \'quantity\': 1000000}, \'method\': \'mpc_make_deposit\', \'id\': 0} -> {\'jsonrpc\': \'2.0\', \'error\': {\'message\': \'Server error\', \'data\': {\'type\': \'InsufficientFunds\', \'message\': "Needed funds \'81879\', available \'0\' for BTC@n493HAuhMuhj1wKKtrcnvNc5uhuWxK79JH", \'args\': ["Needed funds \'81879\', available \'0\' for BTC@n493HAuhMuhj1wKKtrcnvNc5uhuWxK79JH"]}, \'code\': -32000}, \'id\': 0}', 'args': ['Rpc call failed! {\'jsonrpc\': \'2.0\', \'params\': {\'spend_secret_hash\': \'3af9eead9915a477c49ab2bbb66e2967401c5ea6\', \'expire_time\': 1024, \'asset\': \'XCP\', \'payee_pubkey\': \'02b411c282202d2496117f171fb889d6eb4c66a98a3c1ece5a1ca58891f4a92261\', \'payer_pubkey\': \'032e23f28e9595b30f38f92d30286789713092f3706816300ea4bb1a080d8ba443\', \'quantity\': 1000000}, \'method\': \'mpc_make_deposit\', \'id\': 0} -> {\'jsonrpc\': \'2.0\', \'error\': {\'message\': \'Server error\', \'data\': {\'type\': \'InsufficientFunds\', \'message\': "Needed funds \'81879\', available \'0\' for BTC@n493HAuhMuhj1wKKtrcnvNc5uhuWxK79JH", \'args\': ["Needed funds \'81879\', available \'0\' for BTC@n493HAuhMuhj1wKKtrcnvNc5uhuWxK79JH"]}, \'code\': -32000}, \'id\': 0}']}}}
```

**Comment by F483** [comment]
Added more clear error message.
