### ISSUE TITLE
queuepayment negativ quantity

### ISSUE THREAD

**Issue by littleskunk** [F483/picopayments-cli-python#7]
```
picopayments-cli --testnet queuepayment 08ed5def131032029d7194622f59a058a62a75672f2b7c6c8b7e933a34efba87 08dd547aa7f9ce78aa4d4391506d43b0d45b971964fcde344c9c133dfb091be0 -1337
root@micropayment:~/.picopayments# picopayments-cli --testnet sync --handle 08ed5def131032029d7194622f59a058a62a75672f2b7c6c8b7e933a34efba87
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:732: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html (This warning will only appear once by default.)
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/usr/local/bin/picopayments-cli", line 21, in <module>
    result = api.__getattribute__(command)(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/api.py", line 282, in sync
    "received_payments": client.sync()
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/mph.py", line 125, in sync
    handle=self.handle, sends=payments, commit=commit, revokes=revokes
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/rpc.py", line 90, in wrapper
    password=self.password
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/rpc.py", line 53, in auth_jsonrpc_call
    password=password, verify_ssl_cert=verify_ssl_cert)
  File "/usr/local/lib/python3.4/dist-packages/picopayments_cli/rpc.py", line 42, in jsonrpc_call
    raise JsonRpcCallFailed(payload, response)
picopayments_cli.rpc.JsonRpcCallFailed: Rpc call failed! {'params': {'handle': '08ed5def131032029d7194622f59a058a62a75672f2b7c6c8b7e933a34efba87', 'commit': None, 'next_revoke_secret_hash': '51211b95e59573d48b7d363843f4c9d8df9d7541', 'pubkey': '032e23f28e9595b30f38f92d30286789713092f3706816300ea4bb1a080d8ba443', 'revokes': [], 'signature': '3046022100dc55fbdd8c4f1b8005935cb6859fb0a479121df44ee73bb1d5d2677a6a430bda022100f59898ce535023e0c3ed4781dd34b10670b1599fcacb51c8651344958908891d', 'sends': [{'payee_handle': '08dd547aa7f9ce78aa4d4391506d43b0d45b971964fcde344c9c133dfb091be0', 'amount': -1337, 'token': 'a39f0a466c5ac10b7ed3018a557de5ebeb30a79a265be4837057c4035084c0e9'}]}, 'method': 'mph_sync', 'id': 0, 'jsonrpc': '2.0'} -> {'error': {'message': 'Server error', 'code': -32000, 'data': {'type': 'InvalidQuantity', 'message': "Invalid quantity: '-1337'", 'args': ["Invalid quantity: '-1337'"]}}, 'id': 0, 'jsonrpc': '2.0'}
```

**Comment by F483** [comment]
Obviously transferring a negative quantity is invalid and you get an error. You will have to manually remove the queued payment from the ` ~/.picopayments/testnet.data` file.

I will add a remove queued payment command to help with this.
